name: Codacy Security Scan

on:
  push:
    branches: [ "main", "master", "dev_hai" ]
  pull_request:
    branches: [ "main", "master", "dev_hai" ]

jobs:
  codacy-analysis:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          
          # YÊU CẦU 1: Giới hạn vùng quét (Chỉ quét source code, bỏ qua database, target, config...)
          directory: ${{ github.workspace }}/src
          
          # YÊU CẦU 2 & 3: Đẩy Full log (Audit) và nhường quyền Enforce cho Server
          max-allowed-issues: 2147483647
