name: Codacy Security Scan

on:
  push:
    branches: [ "main", "master", "dev_hai" ]
  pull_request:
    branches: [ "main", "master", "dev_hai" ] # Đã bổ sung dev_hai vào đây

jobs:
  codacy-analysis:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647 # Thêm dòng này để Action luôn báo Tick Xanh
